name: coursera2025
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pillow
  - ipython
  - ipykernel
  - notebook
  - jupyterlab
  - nbconvert
  - nbclient
  - nbformat
  - ipywidgets
  - widgetsnbextension
  - pip
  - pip:
      - nbgitpuller
