name: coursera2025
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - ipython
  - ipykernel
  - notebook
  - nbconvert
  - nbclient
  - pip
  - pip:
      - nbgitpuller
